version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gripinvest_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gripinvest
      MYSQL_USER: gripuser
      MYSQL_PASSWORD: grippass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gripinvest_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gripinvest_backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: gripinvest
      DB_USER: root
      DB_PASSWORD: password
      JWT_SECRET: gripinvest_jwt_secret_2025
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - gripinvest_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gripinvest_frontend
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - gripinvest_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  gripinvest_network:
    driver: bridge